language: ruby
cache: bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:metrics"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - rbx-2
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
